#!/usr/bin/env bash
set -Eeuo pipefail

headers=''
body=''
while [[ $# -gt 0 ]]; do
  case "$1" in
    -D)
      headers="$2"
      shift 2
      ;;
    -o)
      body="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

version='v-test-new'
if [[ "${TOKENESS_TEST_CDN_FAILURE:-0}" -eq 1 ]]; then
  version='v-test-old'
fi

printf 'HTTP/2 401\r\nX-New-Api-Version: %s\r\n\r\n' "$version" > "$headers"
printf '{"error":"unauthorized"}\n' > "$body"
printf '401'
